### ISSUE TITLE
Ошибка при отправки большого количества сообщений

### ISSUE THREAD

**Issue by centralhardware** [kukree/tuichat#12]
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 91, in get_data
    data = loads(data)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 58 (char 57)

после отправки большого количества пустых строк возникла данная ошибка

**Comment by k0oda** [comment]
**CLIENT**
![image](https://user-images.githubusercontent.com/39520144/57966126-f3cadd80-796f-11e9-84aa-65c0eec336b0.png)
**SERVER**
![image](https://user-images.githubusercontent.com/39520144/57966128-fdecdc00-796f-11e9-9152-d975ee9dba74.png)

Возможно я протестировал это не в том случае, описанном вами но в случае если проблема осталась я снова открою этот вопрос
