### ISSUE TITLE
Ошибка отправки большого текста 

### ISSUE THREAD

**Issue by centralhardware** [kukree/tuichat#14]
2019-05-09 | 11:49:39  127.0.0.1 - аре́нина» (1873—1877; журнальная публикация 1875—1877; первое книжное издание 1878) — роман Льва Толстого о трагической любви замужней дамы Анны Карениной и блестящего офицера Вронского на фоне счастливой семейной жизни дворян Константина Лёвина[К 1] и Кити Щербацкой. Масштабная картина нравов и быта дворянской среды Петербурга и Москвы второй половины XIX века, сочетающая философские размышления авторского alter ego Лёвина с передовыми в русской литературе психологическими зарисовками, а также сценами из жизни крестьян.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 89, in get_data
    size = int(conn.recv(14).decode('utf-8'))
ValueError: invalid literal for int() with base 10: '106{"sending_t'

**Comment by centralhardware** [comment]
Enter a message or enter "/r" to receive new messages > аре́нина» (1873—1877; журнальная публикация 1875—1877; первое книжное издание 1878) — роман Льва Толстого о трагической любви замужней дамы Анны Карениной и блестящего офицера Вронского на фоне счастливой семейной жизни дворян Константина Лёвина[К 1] и Кити Щербацкой. Масштабная картина нравов и быта дворянской среды Петербурга и Москвы второй половины XIX века, сочетающая философские размышления авторского alter ego Лёвина с передовыми в русской литературе психологическими зарисовками, а также сценами из жизни крестьян.


Содержание
1       О романе
1.1     Композиция романа
2       Прототипы. Характеры. Образы
2.1     Константин Лёвин
2.2     Николай Лёвин
2.3     Анна Аркадьевна Каренина (Облонская)
2.3.1   Характер

со стороны клиента

**Comment by centralhardware** [comment]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 91, in get_data
    data = loads(data)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 390 (char 389)
