### ISSUE TITLE
Ошибка при отправке японского текста

### ISSUE THREAD

**Issue by centralhardware** [kukree/tuichat#15]
2019-05-09 | 11:53:26  127.0.0.1 - 山田さん、どこへ行きますか。
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 89, in get_data
    size = int(conn.recv(14).decode('utf-8'))
ValueError: invalid literal for int() with base 10: '180{"sending_t'

**Comment by k0oda** [comment]
![Screenshot_20190711_151351](https://user-images.githubusercontent.com/39520144/61038299-980c5600-a3ee-11e9-90cc-ad27a9404d60.png)
